use openapi_to_rust::ConfigFile;
use openapi_to_rust::cli::{MAX_REMOTE_SPEC_BYTES, load_spec};
use openapi_to_rust::spec_source::validate_remote_spec_url;
use std::io::{Read, Write};
use std::net::TcpListener;
use std::path::{Path, PathBuf};
use std::process::{Command, Output};
use std::thread;
use tempfile::TempDir;

const SPEC: &str = r#"openapi: 3.1.0
info:
  title: CLI workflow test
  version: 1.0.0
paths:
  /pets:
    get:
      operationId: listPets
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'
components:
  schemas:
    Pet:
      type: object
      required: [name]
      properties:
        name:
          type: string
"#;

fn binary() -> PathBuf {
    PathBuf::from(env!("CARGO_BIN_EXE_openapi-to-rust"))
}

fn run(current_dir: &Path, args: &[&str]) -> Output {
    Command::new(binary())
        .current_dir(current_dir)
        .args(args)
        .output()
        .unwrap()
}

fn assert_success(output: &Output) {
    assert!(
        output.status.success(),
        "command failed\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
}

#[test]
fn client_check_json_keeps_cargo_output_off_stdout() {
    let output = run(
        Path::new(env!("CARGO_MANIFEST_DIR")),
        &[
            "clients",
            "check",
            "--manifest",
            "tests/fixtures/client-sync/openapi-clients.yml",
            "--json",
        ],
    );
    assert_success(&output);
    let report: serde_json::Value =
        serde_json::from_slice(&output.stdout).unwrap_or_else(|error| {
            panic!(
                "client report was not clean JSON: {error}\nstdout:\n{}\nstderr:\n{}",
                String::from_utf8_lossy(&output.stdout),
                String::from_utf8_lossy(&output.stderr)
            )
        });
    assert_eq!(report["mode"], "check");
    assert_eq!(report["clients"][0]["compiled"], true);
}

#[test]
fn direct_generation_supports_client_types_only_dry_run_check_quiet_and_json() {
    let temp = TempDir::new().unwrap();
    std::fs::write(temp.path().join("api.yaml"), SPEC).unwrap();

    let generated = run(
        temp.path(),
        &[
            "generate",
            "api.yaml",
            "--output-dir",
            "generated",
            "--quiet",
        ],
    );
    assert_success(&generated);
    assert!(generated.stdout.is_empty());
    assert!(generated.stderr.is_empty());
    for file in ["types.rs", "client.rs", "mod.rs", "REQUIRED_DEPS.toml"] {
        assert!(temp.path().join("generated").join(file).is_file(), "{file}");
    }
    let types = std::fs::read_to_string(temp.path().join("generated/types.rs")).unwrap();
    assert!(types.contains("Generated by openapi-to-rust v"));
    assert!(types.contains("Source OpenAPI document: api.yaml"));

    let types_only = run(
        temp.path(),
        &[
            "generate",
            "api.yaml",
            "--output-dir",
            "types-only",
            "--types-only",
            "--quiet",
        ],
    );
    assert_success(&types_only);
    assert!(!temp.path().join("types-only/client.rs").exists());
    let type_deps =
        std::fs::read_to_string(temp.path().join("types-only/REQUIRED_DEPS.toml")).unwrap();
    assert!(!type_deps.contains("reqwest"));

    let dry_run = run(
        temp.path(),
        &[
            "generate",
            "api.yaml",
            "--output-dir",
            "preview",
            "--dry-run",
            "--json",
        ],
    );
    assert_success(&dry_run);
    assert!(dry_run.stderr.is_empty());
    assert!(!temp.path().join("preview").exists());
    let summary: serde_json::Value = serde_json::from_slice(&dry_run.stdout).unwrap();
    assert_eq!(summary["status"], "dry-run");
    assert_eq!(summary["source"], "api.yaml");
    assert_eq!(summary["operations"], 1);

    let current = run(
        temp.path(),
        &[
            "generate",
            "api.yaml",
            "--output-dir",
            "generated",
            "--check",
            "--quiet",
        ],
    );
    assert_success(&current);
    assert!(current.stdout.is_empty());
    assert!(current.stderr.is_empty());

    let changed_path = temp.path().join("generated/types.rs");
    std::fs::write(&changed_path, "user edit\n").unwrap();
    let stale = run(
        temp.path(),
        &[
            "generate",
            "api.yaml",
            "--output-dir",
            "generated",
            "--check",
            "--quiet",
        ],
    );
    assert!(!stale.status.success());
    assert!(String::from_utf8_lossy(&stale.stderr).contains("changed: types.rs"));
    assert_eq!(
        std::fs::read_to_string(changed_path).unwrap(),
        "user edit\n"
    );

    let missing = run(
        temp.path(),
        &["generate", "missing.yaml", "--dry-run", "--json"],
    );
    assert!(!missing.status.success());
    assert!(missing.stderr.is_empty());
    let error: serde_json::Value = serde_json::from_slice(&missing.stdout).unwrap();
    assert_eq!(error["status"], "error");
}

#[test]
fn init_creates_a_safe_config_consumed_by_bare_generate() {
    let temp = TempDir::new().unwrap();
    std::fs::write(temp.path().join("pet-store.yaml"), SPEC).unwrap();

    let initialized = run(temp.path(), &["init", "pet-store.yaml", "--quiet"]);
    assert_success(&initialized);
    assert!(initialized.stdout.is_empty());
    assert!(initialized.stderr.is_empty());

    let config_path = temp.path().join("openapi-to-rust.toml");
    let config = ConfigFile::load(&config_path)
        .unwrap()
        .into_generator_config();
    assert!(config.enable_async_client);
    assert!(!config.tracing_enabled);
    assert_eq!(config.module_name, "pet_store");

    let generated = run(temp.path(), &["generate", "--quiet"]);
    assert_success(&generated);
    assert!(temp.path().join("src/generated/types.rs").is_file());
    assert!(temp.path().join("src/generated/client.rs").is_file());

    let original = std::fs::read_to_string(&config_path).unwrap();
    let refused = run(temp.path(), &["init", "pet-store.yaml", "--quiet"]);
    assert!(!refused.status.success());
    assert!(String::from_utf8_lossy(&refused.stderr).contains("refusing to overwrite"));
    assert_eq!(std::fs::read_to_string(&config_path).unwrap(), original);

    let preview = run(
        temp.path(),
        &[
            "init",
            "pet-store.yaml",
            "--config",
            "preview.toml",
            "--types-only",
            "--dry-run",
            "--json",
        ],
    );
    assert_success(&preview);
    assert!(!temp.path().join("preview.toml").exists());
    let summary: serde_json::Value = serde_json::from_slice(&preview.stdout).unwrap();
    assert_eq!(summary["status"], "dry-run");
    assert_eq!(summary["client"], false);
    assert!(
        summary["content"]
            .as_str()
            .unwrap()
            .contains("enable_async_client = false")
    );
}

#[test]
fn server_commands_apply_configured_schema_extensions_but_explicit_spec_is_raw() {
    let temp = TempDir::new().unwrap();
    std::fs::write(temp.path().join("api.yaml"), SPEC).unwrap();
    std::fs::write(
        temp.path().join("sse-overlay.json"),
        r#"{
  "paths": {
    "/pets": {
      "get": {
        "responses": {
          "200": {
            "content": {
              "text/event-stream": {
                "schema": { "type": "object" }
              }
            }
          }
        }
      }
    }
  }
}"#,
    )
    .unwrap();
    std::fs::write(
        temp.path().join("openapi-to-rust.toml"),
        r#"[generator]
spec_path = "api.yaml"
output_dir = "src/gen"
module_name = "api"
schema_extensions = ["sse-overlay.json"]

[features]
enable_async_client = false

[server]
framework = "axum"
operations = []
"#,
    )
    .unwrap();

    let configured_list = run(temp.path(), &["server", "list"]);
    assert_success(&configured_list);
    assert!(
        String::from_utf8_lossy(&configured_list.stdout).contains("/pets  [SSE]"),
        "configured server list did not apply the SSE overlay:\n{}",
        String::from_utf8_lossy(&configured_list.stdout)
    );

    let configured_add = run(temp.path(), &["server", "add", "listPets", "--dry-run"]);
    assert_success(&configured_add);
    assert!(
        String::from_utf8_lossy(&configured_add.stdout).contains("Streaming: yes"),
        "configured server add did not apply the SSE overlay:\n{}",
        String::from_utf8_lossy(&configured_add.stdout)
    );

    let explicit_list = run(temp.path(), &["server", "list", "--spec", "api.yaml"]);
    assert_success(&explicit_list);
    assert!(
        !String::from_utf8_lossy(&explicit_list.stdout).contains("[SSE]"),
        "an explicit --spec unexpectedly applied config extensions:\n{}",
        String::from_utf8_lossy(&explicit_list.stdout)
    );
}

fn serve_once(
    body: &'static str,
    declared_length: Option<u64>,
) -> (String, thread::JoinHandle<()>) {
    let listener = TcpListener::bind("127.0.0.1:0").unwrap();
    let address = listener.local_addr().unwrap();
    let handle = thread::spawn(move || {
        let (mut stream, _) = listener.accept().unwrap();
        let mut request = [0_u8; 4096];
        let _ = stream.read(&mut request).unwrap();
        let length = declared_length.unwrap_or(body.len() as u64);
        write!(
            stream,
            "HTTP/1.1 200 OK\r\nContent-Type: application/yaml\r\nContent-Length: {length}\r\nConnection: close\r\n\r\n{body}"
        )
        .unwrap();
    });
    (format!("http://{address}/openapi.yaml"), handle)
}

#[test]
fn loopback_fetch_is_bounded_and_provenance_redacts_secrets() {
    assert!(validate_remote_spec_url("http://example.com/api.yaml").is_err());
    assert!(validate_remote_spec_url("https://user:secret@example.com/api.yaml").is_err());

    let temp = TempDir::new().unwrap();
    let (base_url, server) = serve_once(SPEC, None);
    let source = format!("{base_url}?token=super-secret#private-fragment");
    let generated = run(
        temp.path(),
        &["generate", &source, "--output-dir", "remote", "--quiet"],
    );
    server.join().unwrap();
    assert_success(&generated);
    let types = std::fs::read_to_string(temp.path().join("remote/types.rs")).unwrap();
    assert!(types.contains(&base_url));
    assert!(types.contains("query redacted"));
    assert!(!types.contains("super-secret"));
    assert!(!types.contains("private-fragment"));
    let dependencies =
        std::fs::read_to_string(temp.path().join("remote/REQUIRED_DEPS.toml")).unwrap();
    assert!(dependencies.contains("query redacted"));
    assert!(!dependencies.contains("super-secret"));

    let (oversized_url, oversized_server) =
        serve_once("", Some(MAX_REMOTE_SPEC_BYTES.saturating_add(1)));
    let error = load_spec(&oversized_url).unwrap_err().to_string();
    oversized_server.join().unwrap();
    assert!(error.contains("response-size limit"), "{error}");
}
