#!/usr/bin/env bash
# Shared corpus generation for scripts/corpus-manifest.sh and scripts/gen-diff.sh.
#
# Both consumers must produce byte-identical output for an unchanged generator,
# or the checked-in manifest and the on-demand diff disagree about what moved.
# Everything that decides those bytes lives here:
#
#   * the per-spec TOML, which mirrors scripts/spec-compile.sh so the manifest
#     describes the same generated code CI compiles;
#   * the Swagger 2.0 skip, matching spec-compile.sh;
#   * corpus_normalize, which erases the "Generated by openapi-to-rust vX.Y.Z.
#     Source OpenAPI document: <path>" stamp. Left alone, a version bump or a
#     different checkout path would rewrite every hash and bury a real change
#     in noise.
#
# Source this file; it defines functions only.

# Emit "name|relative-spec-path" per spec, sorted. Args, when given, whitelist
# spec names.
corpus_specs() {
  local want=("$@") spec name keep w
  while IFS= read -r spec; do
    name="$(basename "$spec")"
    name="${name%.*}"
    if [ ${#want[@]} -gt 0 ]; then
      keep=0
      for w in "${want[@]}"; do [ "$w" = "$name" ] && keep=1; done
      [ $keep -eq 0 ] && continue
    fi
    # Swagger 2.0 is out of scope for this generator (same test as
    # spec-compile.sh): a `swagger: 2.x` key with no `openapi:` key.
    if grep -qE '("swagger"[[:space:]]*:|swagger[[:space:]]*:)[[:space:]]*"?2\.' "$spec" 2>/dev/null \
       && ! grep -qE '("openapi"[[:space:]]*:|openapi[[:space:]]*:)' "$spec" 2>/dev/null; then
      continue
    fi
    printf '%s|%s\n' "$name" "$spec"
  done < <(find specs -maxdepth 1 -type f \( -name '*.yaml' -o -name '*.json' \) | sort)
}

# corpus_normalize <dir> — strip the version/source stamp from every generated
# file in <dir> so hashes depend only on the generated code itself.
corpus_normalize() {
  local dir="$1"
  find "$dir" -type f \( -name '*.rs' -o -name '*.toml' \) -print0 \
    | xargs -0 perl -pi -e 's/(Generated by openapi-to-rust ).*/${1}<normalized>/'
}

# corpus_build <manifest-dir> <target-dir> [profile] — build the generator from
# the checkout at <manifest-dir>, into <target-dir>. Echoes the binary path.
# Default profile is release: debug generation of microsoft-graph alone takes
# ~56s against ~9s release, and the corpus is generated twice per diff.
corpus_build() {
  local src="$1" target="$2" profile="${3:-release}" flag=""
  [ "$profile" = "release" ] && flag="--release"
  cargo build $flag --bin openapi-to-rust \
    --manifest-path "$src/Cargo.toml" --target-dir "$target" >&2
  printf '%s/%s/openapi-to-rust\n' "$target" "$profile"
}

# corpus_generate <gen-bin> <out-root> [spec names...] — generate every spec
# into <out-root>/<name>/, normalized. Returns non-zero if any spec fails; the
# failures are echoed to stderr as "GEN-FAIL <name>".
#
# Run from the repository root: spec paths are resolved against it, so both
# sides of a diff read the same pinned specs and the diff isolates the
# generator change.
corpus_generate() {
  local gen_bin="$1" out_root="$2"; shift 2
  local name spec dir module rc=0
  # The generator resolves a relative output_dir against the config file's own
  # directory, which would nest the output under a duplicated path. Anchor it.
  mkdir -p "$out_root"
  out_root="$(cd "$out_root" && pwd)"
  while IFS='|' read -r name spec; do
    [ -z "$name" ] && continue
    dir="$out_root/$name"
    mkdir -p "$dir"
    module="$(echo "$name" | tr '-' '_')"
    cat >"$dir/openapi-to-rust.toml" <<EOF
[generator]
spec_path = "$PWD/$spec"
output_dir = "$dir"
module_name = "$module"

[features]
enable_async_client = true

[http_client]
base_url = "https://example.invalid"
timeout_seconds = 60
EOF
    if ! "$gen_bin" generate --config "$dir/openapi-to-rust.toml" --quiet \
         >"$dir/generate.log" 2>&1; then
      echo "GEN-FAIL $name" >&2
      rc=1
      continue
    fi
    rm -f "$dir/openapi-to-rust.toml" "$dir/generate.log"
  done < <(corpus_specs "$@")
  corpus_normalize "$out_root"
  return $rc
}

# corpus_hash <file> — first 16 hex chars of the file's SHA-256.
corpus_hash() {
  if command -v shasum >/dev/null 2>&1; then
    shasum -a 256 "$1" | cut -c1-16
  else
    sha256sum "$1" | cut -c1-16
  fi
}
