#!/usr/bin/env bash
# Write or verify tests/corpus-manifest.txt: one hashed line per file generated
# from every spec in specs/.
#
# The manifest is the tripwire, not the record. It is small enough to read in a
# review and answers "did this generator change move real-world output, and for
# which specs?" — it deliberately does not store the code. To see what actually
# changed, run scripts/gen-diff.sh <base-ref>, which reconstructs the old output
# from the pinned specs.
#
# Usage:
#   scripts/corpus-manifest.sh            # regenerate the manifest in place
#   scripts/corpus-manifest.sh --check    # fail if the manifest is out of date
#   scripts/corpus-manifest.sh --check --from tmp/gen-diff/head
#                                         # hash a corpus that is already on
#                                         # disk instead of generating one
#
# Env:
#   CORPUS_PROFILE=debug   build the generator without --release (slower to run)
set -euo pipefail
cd "$(dirname "$0")/.."
source scripts/lib/corpus.sh

MANIFEST="tests/corpus-manifest.txt"
CHECK=0
FROM=""
while [ $# -gt 0 ]; do
  case "$1" in
    --check) CHECK=1 ;;
    --from) FROM="${2:?--from needs a directory}"; shift ;;
    *) echo "usage: $0 [--check] [--from <corpus-dir>]" >&2; exit 2 ;;
  esac
  shift
done

WORK="tmp/corpus-manifest"
rm -rf "$WORK"
mkdir -p "$WORK"
# Keep the scratch tree when something failed: corpus_generate leaves the
# generator log for the spec that broke.
cleanup() {
  local code=$?
  if [ "$code" -eq 0 ] || [ ! -d "$WORK/out" ]; then
    rm -rf "$WORK"
  else
    echo "[corpus-manifest] work dir kept: $WORK" >&2
  fi
}
trap cleanup EXIT

if [ -n "$FROM" ]; then
  # Reuse a corpus another script already generated (scripts/gen-diff.sh leaves
  # one at tmp/gen-diff/head) rather than generating a third copy. It must be
  # complete, or missing specs would read as deletions.
  SRC="$FROM"
  expected=$(corpus_specs | wc -l | tr -d ' ')
  found=$(find "$SRC" -maxdepth 1 -mindepth 1 -type d | wc -l | tr -d ' ')
  if [ "$expected" != "$found" ]; then
    echo "[corpus-manifest] $SRC holds $found of $expected specs; refusing a partial manifest" >&2
    exit 2
  fi
else
  SRC="$WORK/out"
  echo "[corpus-manifest] building generator..." >&2
  GEN_BIN="$(corpus_build "$PWD" "$PWD/target" "${CORPUS_PROFILE:-release}")"

  echo "[corpus-manifest] generating corpus..." >&2
  corpus_generate "$GEN_BIN" "$SRC"
fi

OUT="$WORK/manifest.txt"
{
  echo "# openapi-to-rust corpus manifest"
  echo "#"
  echo "# SHA-256 (first 16 hex) of every file generated from the specs pinned in"
  echo "# specs/. Regenerate with scripts/corpus-manifest.sh; CI verifies it with"
  echo "# --check. A diff here means a generator change moved real-world output:"
  echo "# confirm that was intended, then see exactly what moved with"
  echo "#   scripts/gen-diff.sh <base-ref>"
  echo "#"
  echo "# The \"Generated by openapi-to-rust vX.Y.Z\" stamp is normalized away, so a"
  echo "# version bump alone never touches this file."
  echo "#"
  echo "# columns: path  bytes  lines  sha256[0:16]"
} >"$OUT"

files=0
bytes=0
while IFS= read -r f; do
  rel="${f#"$SRC/"}"
  b=$(wc -c <"$f" | tr -d ' ')
  l=$(wc -l <"$f" | tr -d ' ')
  printf '%-52s %10s %8s %s\n' "$rel" "$b" "$l" "$(corpus_hash "$f")" >>"$OUT"
  files=$((files + 1))
  bytes=$((bytes + b))
done < <(find "$SRC" -type f | sort)

specs=$(find "$SRC" -maxdepth 1 -mindepth 1 -type d | wc -l | tr -d ' ')
printf '#\n# specs: %s   files: %s   bytes: %s\n' "$specs" "$files" "$bytes" >>"$OUT"

if [ "$CHECK" = "1" ]; then
  if diff -u "$MANIFEST" "$OUT" >"$WORK/manifest.diff"; then
    echo "[corpus-manifest] up to date ($specs specs, $files files)"
    exit 0
  fi
  echo "[corpus-manifest] generated corpus output changed:" >&2
  cat "$WORK/manifest.diff" >&2
  cat >&2 <<'EOF'

This generator change moves the code emitted for real-world specs. If that was
intended, inspect the change with

  scripts/gen-diff.sh <base-ref>

then refresh the manifest with

  scripts/corpus-manifest.sh
EOF
  exit 1
fi

mkdir -p "$(dirname "$MANIFEST")"
cp "$OUT" "$MANIFEST"
echo "[corpus-manifest] wrote $MANIFEST ($specs specs, $files files)"
