#!/usr/bin/env bash
# Report how much of the generated surface is still `serde_json::Value`, and
# why, across every spec under specs/.
#
# `serde_json::Value` in generated code means one of two things: the schema
# declared an unconstrained value, or the generator dropped type information the
# schema carried. Only the second is a defect, so the report separates them and
# ranks the recoverable causes — that ranking is what says where typing work is
# worth doing next.
#
# Usage:
#   scripts/untyped-census.sh            # rewrite the checked-in report
#   scripts/untyped-census.sh --check    # fail if the report is out of date
#
# Env:
#   CENSUS_SPECS="a b"  limit to named specs (default: everything in specs/)
set -euo pipefail
cd "$(dirname "$0")/.."

REPORT="tests/conformance/untyped-report.md"
CHECK=0
[ "${1:-}" = "--check" ] && CHECK=1

echo "[untyped-census] building openapi-to-rust binary..." >&2
cargo build --quiet --bin openapi-to-rust

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

specs=()
if [ -n "${CENSUS_SPECS:-}" ]; then
  for name in $CENSUS_SPECS; do
    for candidate in "specs/$name.yaml" "specs/$name.json"; do
      [ -f "$candidate" ] && specs+=("$candidate")
    done
  done
else
  for candidate in specs/*.yaml specs/*.json; do
    [ -f "$candidate" ] && specs+=("$candidate")
  done
fi

for spec in "${specs[@]}"; do
  name="$(basename "$spec")"; name="${name%.*}"
  if ! target/debug/openapi-to-rust generate "$spec" \
      --output-dir "$WORK/$name" --types-only --report-untyped --json \
      > "$WORK/$name.json" 2>/dev/null; then
    echo "[untyped-census] skipped $name (generation failed)" >&2
    rm -f "$WORK/$name.json"
    continue
  fi
  # The findings array is followed by the generation summary; keep the array.
  jq -s '.[0]' "$WORK/$name.json" > "$WORK/$name.findings.json"
done

{
  echo "# Untyped Output Census"
  echo
  echo "Generated by \`scripts/untyped-census.sh\`. Every generated field that"
  echo "carries \`serde_json::Value\`, grouped by why."
  echo
  echo "**Faithful** means the schema declared an unconstrained value and there is"
  echo "no better Rust type. **Recoverable** means the schema carried type"
  echo "information that did not survive; those are defects with a fix."
  echo
  echo "## Corpus totals"
  echo
  echo "| Reason | Count | Verdict |"
  echo "|---|---:|---|"
  jq -s -r '
    add
    | group_by(.reason)
    | map({reason: .[0].reason, count: length})
    | sort_by(-.count)
    | .[]
    | "| `\(.reason)` | \(.count) | " +
      (if (.reason | test("^(any-schema|opaque-object|untyped-additional-properties|array-without-items|open-positional-items)$"))
       then "faithful" else "**recoverable**" end) + " |"
  ' "$WORK"/*.findings.json
  echo
  echo "## Per spec"
  echo
  echo "| Spec | Untyped | Recoverable |"
  echo "|---|---:|---:|"
  for findings in "$WORK"/*.findings.json; do
    name="$(basename "$findings")"; name="${name%.findings.json}"
    total="$(jq 'length' "$findings")"
    recoverable="$(jq '[.[] | select(.reason | test("^(any-schema|opaque-object|untyped-additional-properties|array-without-items|open-positional-items)$") | not)] | length' "$findings")"
    echo "| \`$name\` | $total | $recoverable |"
  done
} > "$WORK/report.md"

if [ "$CHECK" = "1" ]; then
  if ! diff -u "$REPORT" "$WORK/report.md"; then
    echo "[untyped-census] $REPORT is out of date; run scripts/untyped-census.sh" >&2
    exit 1
  fi
  echo "[untyped-census] ✅ report is up to date"
else
  cp "$WORK/report.md" "$REPORT"
  echo "[untyped-census] wrote $REPORT"
fi
